# Auto assignment of reviewers based on PR labels
pullRequestOpened: true
ignoreDraft: true

reviewers:
  - PranjaySrivastava
  - Salil-IND
  - gopal45-dev

requestReviewers: author

numberOfReviewers: 2

skipKeywords:
  - wip
  - draft