/**
 * Visual Engine Service
 * Generates and validates algorithm/data-structure visual sequence plans
 * for Canvas and SVG rendering on the frontend avatar learning interface.
 */

class VisualEngineService {
  /**
   * Validate and enrich a visual sequence returned from LLM or generated by template
   * @param {Object} rawSequence
   * @param {string} topic
   * @returns {Object} Standardized visual sequence matching frontend specs
   */
  normalizeSequence(rawSequence, topic = 'general') {
    if (!rawSequence || typeof rawSequence !== 'object') {
      return this.generateTemplate('algorithm_execution', topic);
    }

    const type = rawSequence.type || 'algorithm_execution';
    const title = rawSequence.title || `Visualizing ${topic}`;
    const rawSteps = Array.isArray(rawSequence.steps) ? rawSequence.steps : [];

    const steps = rawSteps.map((step, idx) => ({
      step: typeof step.step === 'number' ? step.step : idx + 1,
      action: step.action || 'highlight',
      description: step.description || `Step ${idx + 1}`,
      elements: Array.isArray(step.elements) ? step.elements : step.indices || [],
      indices: Array.isArray(step.indices) ? step.indices : step.elements || [],
      values: Array.isArray(step.values) ? step.values : [],
      metadata: step.metadata || {},
    }));

    // If no steps provided, populate with a generic 3-step sequence
    if (steps.length === 0) {
      steps.push(
        {
          step: 1,
          action: 'highlight',
          description: 'Initialize algorithm structure',
          elements: [0],
        },
        {
          step: 2,
          action: 'compare',
          description: 'Process elements and evaluate condition',
          elements: [0, 1],
        },
        { step: 3, action: 'swap', description: 'Update state / conclude step', elements: [1] }
      );
    }

    return {
      type,
      title,
      topic,
      totalSteps: steps.length,
      timing: {
        codeDisplayAt: 0,
        visualStartAt: 3000, // 3 seconds in, as specified in PDF
        visualCompleteAt: 7000, // 7 seconds in
      },
      steps,
    };
  }

  /**
   * Generate canonical step-by-step visual sequences for standard algorithms
   * @param {string} type - 'sorting' | 'searching' | 'tree' | 'graph' | 'complexity' | 'linked_list'
   * @param {string} algorithmName - e.g. 'quicksort', 'binary_search', etc.
   */
  generateTemplate(type, algorithmName = '') {
    const normType = (type || '').toLowerCase();
    const normName = algorithmName.toLowerCase().replace(/[^a-z0-9]/g, '');

    if (
      normType === 'tree' ||
      (!normType && (normName.includes('tree') || normName.includes('bst')))
    ) {
      return this.generateBstTemplate();
    }
    if (
      normType === 'graph' ||
      (!normType &&
        (normName.includes('graph') || normName.includes('bfs') || normName.includes('dfs')))
    ) {
      return this.generateGraphTraversalTemplate(normName.includes('dfs') ? 'DFS' : 'BFS');
    }
    if (
      normType === 'complexity' ||
      (!normType && (normName.includes('bigo') || normName.includes('complexity')))
    ) {
      return this.generateComplexityTemplate();
    }
    if (
      normType === 'searching' ||
      (!normType && (normName.includes('binary') || normName.includes('search')))
    ) {
      return this.generateBinarySearchTemplate();
    }
    if (normType === 'sorting' || normName.includes('sort') || normName.includes('quick')) {
      return this.generateQuickSortTemplate();
    }

    // Default sorting template
    return this.generateQuickSortTemplate();
  }

  generateQuickSortTemplate() {
    const initialArray = [38, 27, 43, 3, 9, 82, 10];
    return {
      type: 'algorithm_visualization',
      subtype: 'sorting',
      title: 'QuickSort Partitioning & Recursive Sorting',
      topic: 'QuickSort',
      initialState: { array: initialArray },
      timing: {
        codeDisplayAt: 0,
        visualStartAt: 3000,
        visualCompleteAt: 7000,
      },
      steps: [
        {
          step: 1,
          action: 'highlight',
          description: 'Select pivot element (last element: 10)',
          elements: [6],
          pivotIndex: 6,
          pivotValue: 10,
          currentArray: [38, 27, 43, 3, 9, 82, 10],
        },
        {
          step: 2,
          action: 'compare',
          description: 'Compare element 38 with pivot 10 (38 > 10, do not swap)',
          elements: [0, 6],
          currentArray: [38, 27, 43, 3, 9, 82, 10],
        },
        {
          step: 3,
          action: 'compare',
          description:
            'Compare element 3 with pivot 10 (3 <= 10, swap with smaller partition pointer)',
          elements: [3, 6],
          currentArray: [38, 27, 43, 3, 9, 82, 10],
        },
        {
          step: 4,
          action: 'swap',
          description: 'Swap 38 and 3 to move smaller element left',
          elements: [0, 3],
          currentArray: [3, 27, 43, 38, 9, 82, 10],
        },
        {
          step: 5,
          action: 'swap',
          description: 'Place pivot 10 in its final sorted position between partitions',
          elements: [2, 6],
          currentArray: [3, 9, 10, 38, 27, 82, 43],
        },
        {
          step: 6,
          action: 'highlight',
          description:
            'Pivot 10 is now in sorted position; recursively sort left [3, 9] and right [38, 27, 82, 43]',
          elements: [2],
          currentArray: [3, 9, 10, 27, 38, 43, 82],
        },
      ],
    };
  }

  generateBinarySearchTemplate() {
    const array = [2, 5, 8, 12, 16, 23, 38, 56, 72, 91];
    const target = 23;
    return {
      type: 'algorithm_visualization',
      subtype: 'searching',
      title: 'Binary Search on Sorted Array',
      topic: 'Binary Search',
      initialState: { array, target },
      steps: [
        {
          step: 1,
          action: 'highlight',
          description: 'Set low = 0 (val: 2), high = 9 (val: 91). Calculate mid = 4 (val: 16)',
          elements: [0, 4, 9],
          indices: [0, 4, 9],
        },
        {
          step: 2,
          action: 'compare',
          description:
            'Compare target 23 with mid 16 (23 > 16) -> Search right half. Set low = mid + 1 = 5',
          elements: [4],
        },
        {
          step: 3,
          action: 'highlight',
          description: 'Set low = 5 (val: 23), high = 9 (val: 91). Calculate mid = 7 (val: 56)',
          elements: [5, 7, 9],
        },
        {
          step: 4,
          action: 'compare',
          description:
            'Compare target 23 with mid 56 (23 < 56) -> Search left half. Set high = mid - 1 = 6',
          elements: [7],
        },
        {
          step: 5,
          action: 'highlight',
          description: 'Set low = 5, high = 6. Mid = 5 (val: 23). Match found!',
          elements: [5],
        },
      ],
    };
  }

  generateBstTemplate() {
    return {
      type: 'data_structure',
      subtype: 'tree',
      title: 'Binary Search Tree Insertion & Search',
      topic: 'Binary Search Tree',
      nodes: [
        { id: 'n1', value: 50, left: 'n2', right: 'n3', x: 200, y: 40 },
        { id: 'n2', value: 30, left: 'n4', right: 'n5', x: 120, y: 110 },
        { id: 'n3', value: 70, left: 'n6', right: 'n7', x: 280, y: 110 },
        { id: 'n4', value: 20, left: null, right: null, x: 80, y: 180 },
        { id: 'n5', value: 40, left: null, right: null, x: 160, y: 180 },
        { id: 'n6', value: 60, left: null, right: null, x: 240, y: 180 },
        { id: 'n7', value: 80, left: null, right: null, x: 320, y: 180 },
      ],
      steps: [
        {
          step: 1,
          action: 'traverse',
          description: 'Start at root node (50). Compare search key 40 < 50',
          elements: ['n1'],
        },
        {
          step: 2,
          action: 'traverse',
          description: 'Move to left child (30). Compare key 40 > 30',
          elements: ['n2'],
        },
        {
          step: 3,
          action: 'highlight',
          description: 'Move to right child (40). Key match confirmed!',
          elements: ['n5'],
        },
      ],
    };
  }

  generateGraphTraversalTemplate(mode = 'BFS') {
    return {
      type: 'graph_traversal',
      subtype: mode.toLowerCase(),
      title: `${mode} Graph Traversal with Visitation Order`,
      topic: `${mode} Traversal`,
      nodes: ['A', 'B', 'C', 'D', 'E', 'F'],
      edges: [
        ['A', 'B'],
        ['A', 'C'],
        ['B', 'D'],
        ['B', 'E'],
        ['C', 'F'],
      ],
      steps:
        mode === 'BFS'
          ? [
              {
                step: 1,
                action: 'highlight',
                description: 'Enqueue root node A; visited: [A]',
                elements: ['A'],
              },
              {
                step: 2,
                action: 'traverse',
                description: 'Dequeue A, enqueue neighbors B and C; visited: [A, B, C]',
                elements: ['A', 'B', 'C'],
              },
              {
                step: 3,
                action: 'traverse',
                description: 'Dequeue B, enqueue neighbors D and E; visited: [A, B, C, D, E]',
                elements: ['B', 'D', 'E'],
              },
              {
                step: 4,
                action: 'highlight',
                description:
                  'Dequeue C, enqueue neighbor F; traversal complete: [A, B, C, D, E, F]',
                elements: ['C', 'F'],
              },
            ]
          : [
              {
                step: 1,
                action: 'highlight',
                description: 'Visit node A; push to call stack',
                elements: ['A'],
              },
              {
                step: 2,
                action: 'traverse',
                description: 'Recurse into neighbor B; call stack: [A, B]',
                elements: ['B'],
              },
              {
                step: 3,
                action: 'traverse',
                description: 'Recurse into neighbor D (leaf); backtrack to B',
                elements: ['D'],
              },
              {
                step: 4,
                action: 'traverse',
                description: 'Recurse into neighbor E; call stack: [A, B, E]',
                elements: ['E'],
              },
              {
                step: 5,
                action: 'highlight',
                description: 'Backtrack to A, recurse into C then F; traversal complete',
                elements: ['C', 'F'],
              },
            ],
    };
  }

  generateComplexityTemplate() {
    return {
      type: 'complexity_analysis',
      title: 'Big-O Algorithm Performance Comparison Curves',
      topic: 'Complexity Analysis',
      curves: [
        { notation: 'O(1)', label: 'Constant', color: '#10B981', formula: '1' },
        { notation: 'O(log n)', label: 'Logarithmic', color: '#3B82F6', formula: 'Math.log2(n)' },
        { notation: 'O(n)', label: 'Linear', color: '#F59E0B', formula: 'n' },
        {
          notation: 'O(n log n)',
          label: 'Linearithmic',
          color: '#8B5CF6',
          formula: 'n * Math.log2(n)',
        },
        { notation: 'O(n^2)', label: 'Quadratic', color: '#EF4444', formula: 'n * n' },
      ],
      steps: [
        {
          step: 1,
          action: 'highlight',
          description: 'O(1) and O(log n): Excellent scalability for large input sizes',
          elements: ['O(1)', 'O(log n)'],
        },
        {
          step: 2,
          action: 'highlight',
          description:
            'O(n) and O(n log n): Efficient for standard sorting like MergeSort and QuickSort',
          elements: ['O(n)', 'O(n log n)'],
        },
        {
          step: 3,
          action: 'compare',
          description: 'O(n^2): BubbleSort/Nested loops rapidly degrade with large arrays',
          elements: ['O(n^2)'],
        },
      ],
    };
  }
}

const visualEngineService = new VisualEngineService();

module.exports = {
  VisualEngineService,
  visualEngineService,
};
